### ISSUE TITLE
Find a way to deploy beta versions / create a proper release workflow

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [hermitdemschoenenleben/linien#165]
--> https://github.com/hermitdemschoenenleben/linien/wiki

# Don't forget
* [x] CHANGELOG.md
* [ x VERSION file
* [x] github release
* [x] `latest_version` file
* [x] flathub

# Subtasks
* [x] fpga image --> build it locally due to need for vivado
* [x] pypi: gui client, python client and server. As server required fpga image, it's probably best to just build it locally
  * [x] how to upload beta versions to pypi? --> **use 0.4.3dev0** scheme
    * [x] client has to be capable of installing correct server version
    * [x] "new version available?" checker has to cope with it
* [ ] pyinstaller
  * [ ] windows
  * [ ] linux
* [ ] flathub

**Comment by bleykauf** [comment]
Maybe have a look into [versioneer](https://github.com/python-versioneer/python-versioneer) and github actions.
